version: '3.8'
services:
  db:
    image: postgres:14.7-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rss
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rssagg
    volumes:
      - data:/var/lib/postgresql/data
 
volumes:
  data:
